#!/bin/bash
#                 _   _                 _     _
#   ___  ___ ___ | |_| |_ ______ _  ___| |__ / |
#  / __|/ __/ _ \| __| __|_  / _` |/ __| '_ \| |
#  \__ \ (_| (_) | |_| |_ / / (_| | (__| | | | |
#  |___/\___\___/ \__|\__/___\__,_|\___|_| |_|_|
#
#       Zac Scott (github.com/scottzach1)
#
# sxhkd config file

##==========================================##
#                         *** Invocation related settings ***                     #
##=======================================##

# terminal emulator
super + Return
	terminator  # kitty

# program launcher
super + @space
	rofi -show run

# emoji keeb
super + period
	emote

# window selector
super + alt + @space
	rofi -show window

# make sxhkd reload its configuration files:
super + alt + s
	pkill -USR1 -x sxhkd

# relaunch polybar
super + alt + p
	sh $HOME/.config/polybar/launch.sh

# quit/restart picom
super + alt + {_,shift + }t
  eval 'pkill picom && sleep 0.1s || true' && picom -b \
    --config=$HOME/.config/picom/{picom,picom-video}.conf

# lockscreen
super + shift + x
	betterlockscreen --lock

# Browser
super + b
	firefox
	#microsoft-edge-stable

# PyCharm
super + p
	pycharm-professional

# WebStorm
super + w
	webstorm

# Obsidian
super + o
	obsidian

# KeepassXC
super + k
	keepassxc

# Thunar
super + t
	thunar


# 1password
super + shift + 1
	1password

##==========================================##
#                         *** Bspwm related hotkeys ***                           #
##=======================================##

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}

# close and kill
super + {_,shift + }q
	bspc node -{c,k}

super + {_,shift + }Delete
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest node
super + g
	bspc node -s biggest

# Increase/decrease window gap on focused desktop
super + ctrl + bracket{left,right}
	bspc config -d focused window_gap $((`bspc config -d focused window_gap` {-,+} 5 ))

# Circulate leaves of the tree
super + {_,shift + }c
	bspc node @/ --circulate {forward,backward}

# Rotate entire tree
super + {_,shift + }r
	bspc node @/ --rotate {90,-90}

# Rotate window with parent
super + {_,ctrl + }r
	bspc node @parent --rotate {90,-90}

## Restore entire tree (Anti balance)
#super + {_,shift + }b
#	bspc node @/ --{balance,equalize}
#
## Restore entire tree (Anti balance)
#super + {_,shift + }Insert
#	bspc node @/ --{balance,equalize}

super + shift + Insert
	bspc node -p south; \
	xterm -e "bspc node @/ --balance; bspc node -c"

super + Insert
	bspc node @/ --balance

##==========================================##
#                         *** Bspwm state & flags settings ***                    #
##=======================================##

# set the window state
super + {t,shift + t,s,f}
	if ! bspc node -t {tiled,pseudo_tiled,floating,fullscreen}; bspc node -t tiled; end;

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

##==========================================##
#                         *** Bspwm focus & swap settings  ***                     #
##=======================================##

# focus the node in the given direction
super + {_,shift + }{j,k,l,semicolon}
	bspc node -{f,s} {west,south,north,east}

super + {Left,Down,Up,Right}
	bspc node -f {west,south,north,east}

super + shift + {Left,Down,Up,Right}
        dir={west,south,north,east}; \
	bspc node -s "$dir" --follow || bspc node -m "$dir" --follow;

super + shift + alt + {Left,Down,Up,Right
	bspc node -m "{west,south,north,east}" --follow;

# also select the node in the given direction
super + ctrl + alt {j,k,l,semicolon}
	bspc node -f @{west,south,noth,east}

super + ctrl + alt {Left,Down,Up,Right}
	bspc node -f @{west,south,noth,east}

# focus the node for the given path jump
#super + {p,b,comma,period}
#	bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
#super + {_,shift + }c
#	bspc node -f {next,prev}.local

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

super + {Prior,Next}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

super + shift {Next, Prior}
	bspc node -d {next, prev}

##==========================================##
#                         *** Bspwm preselect settings ***                        #
##=======================================##

# preselect the direction
super + ctrl + {j,k,l,semicolon}
	bspc node -p {west,south,north,east}

super + ctrl + {Left,Down,Up,Right}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

##==========================================##
#                         *** Bspwm move & resize settings ***                    #
##=======================================##

# expand a window by moving one of its side outward
super + alt + {j,k,l,semicolon}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

super + alt + {Left,Down,Up,Right}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {j,k,l,semicolon}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

super + alt + shift + {Left,Down,Up,Right}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
#super + {Left,Down,Up,Right}
#	bspc node -v {-20 0,0 20,0 -20,20 0}

##==========================================##
#                         *** Application binding settings ***                    #
##=======================================##

super + shift + s
	flameshot gui

##==========================================##
#                         *** Scratchpad related settings ***                     #
##=======================================##

super + u
	bash scratchpad.sh dropdown

##==========================================##
#                         *** Tabbed binding settings ***                         #
##=======================================##

# https://www.reddit.com/r/bspwm/comments/etfm3m/for_those_who_like_tabs/

# Add focused window to a tabbed instance in given direction

super + z; {Left,Down,Up,Right}
	bash tabc.sh (bspc query -N -n {west,south,north,east}) add (bspc query -N -n focused)

# Remove one tab from tabbed
super + z; r
    	set tabbed (bspc query -N -n focused) \
	set child (bash ~/.config/sxhkd/tabc.sh $tabbed list | head -n1) \
	bash tabc.sh $tabbed remove $child

##==========================================##
#                      *** Multimedia key binding settings ***                    #
##=======================================##

# Screen brightness controls
XF86MonBrightnessUp
	xbacklight -inc 5
XF86MonBrightnessDown
	xbacklight -dec 5

# Audio volume cnotrols (pulseaudio)
XF86AudioRaiseVolume
	amixer set Master 5%+
	# pactl set-sink-volume @DEFAULT_SINK@ +1000
XF86AudioLowerVolume
	amixer set Master 5%-
	# pactl set-sink-volume @DEFAULT_SINK@ -1000
XF86AudioMute
	amixer set Master toggle
	# pactl set-sink-mute @DEFAULT_SINK@ toggle

# Media Control (playerctl)
XF86AudioPlay
	playerctl play-pause
XF86AudioNext
	playerctl next
XF86AudioPrev
	playerctl previous
