#!/bin/fish
#                 _   _                 _     _
#   ___  ___ ___ | |_| |_ ______ _  ___| |__ / |
#  / __|/ __/ _ \| __| __|_  / _` |/ __| '_ \| |
#  \__ \ (_| (_) | |_| |_ / / (_| | (__| | | | |
#  |___/\___\___/ \__|\__/___\__,_|\___|_| |_|_|
#
#       Zac Scott (github.com/scottzach1)
#
# sxhkd config file
#

##==========================================##
#                         *** Invocation related settings ***                     #
##=======================================##

# terminal emulator
super + Return
	kitty

# program launcher
super + @space
	rofi -show run

# window selector
super + alt + @space
	rofi -show window

# make sxhkd reload its configuration files:
super + alt + s
	pkill -USR1 -x sxhkd

# relaunch polybar
super + alt + p
	sh $HOME/.config/polybar/launch.sh

# quit/restart picom
super + alt + t
	if pgrep picom; pkill picom; else; picom -b; end;

# lockscreen
super + shift + x
	betterlockscreen --lock

##==========================================##
#                         *** Bspwm related hotkeys ***                           #
##=======================================##

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}

# close and kill
super + {_,shift + }q
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest node
super + g
	bspc node -s biggest

# Increase/decrease window gap on focused desktop
super + ctrl + bracket{left,right}
	bspc config -d focused window_gap $((`bspc config -d focused window_gap` {-,+} 5 ))

# Circulate leaves of the tree
super + {_,shift + }c
	bspc node @/ --circulate {forward,backward}

# Rotate entire tree
super + {_,shift + }r
	bspc node @/ --rotate {90,-90}

# Restore entire tree (Anti balance)
super + {_,shift + }b
	bspc node @/ --{balance,equalize}

##==========================================##
#                         *** Bspwm state & flags settings ***                    #
##=======================================##

# set the window state
super + {t,shift + t,s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

##==========================================##
#                         *** Bspwm focus & swap settings  ***                     #
##=======================================##

# focus the node in the given direction
super + {_,shift + }{j,k,l,semicolon}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
#super + {p,b,comma,period}
#	bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
#super + {_,shift + }c
#	bspc node -f {next,prev}.local

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

##==========================================##
#                         *** Bspwm preselect settings ***                        #
##=======================================##

# preselect the direction
super + ctrl + {j,k,l,semicolon}
	bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

##==========================================##
#                         *** Bspwm move & resize settings ***                    #
##=======================================##

# expand a window by moving one of its side outward
super + alt + {j,k,l,semicolon}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {j,k,l,semicolon}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

##==========================================##
#                         *** Application binding settings ***                    #
##=======================================##

super + shift + s
	flameshot gui

##==========================================##
#                      *** Multimedia key binding settings ***                    #
##=======================================##

# Screen brightness controls (enlighten)
XF86MonBrightnessUp
	enlighten +5%
XF86MonBrightnessDown
	enlighten -5%

# Audio volume cnotrols (pulseaudio)
XF86AudioRaiseVolume
	pactl set-sink-volume @DEFAULT_SINK@ +1000
XF86AudioLowerVolume
	pactl set-sink-volume @DEFAULT_SINK@ -1000
XF86AudioMute
	pactl set-sink-mute @DEFAULT_SINK@ toggle

# Media Control (playerctl)
XF86AudioPlay
	playerctl play-pause
XF86AudioNext
	playerctl next
XF86AudioPrev
	playerctl previous
