# Catppuccin Latte (light) — swapped in by darkman -> current-theme.conf
foreground #4c4f69
background #eff1f5
selection_foreground #eff1f5
selection_background #dc8a78
cursor #dc8a78
cursor_text_color #eff1f5
url_color #dc8a78

active_tab_foreground   #dce0e8
active_tab_background   #8839ef
inactive_tab_foreground #4c4f69
inactive_tab_background #e6e9ef

color0 #5c5f77
color8 #6c6f85
color1 #d20f39
color9 #d20f39
color2 #40a02b
color10 #40a02b
color3 #df8e1d
color11 #df8e1d
color4 #1e66f5
color12 #1e66f5
color5 #ea76cb
color13 #ea76cb
color6 #179299
color14 #179299
color7 #acb0be
color15 #bcc0cc
