#! /bin/sh
#                 _   _                 _     _
#   ___  ___ ___ | |_| |_ ______ _  ___| |__ / |
#  / __|/ __/ _ \| __| __|_  / _` |/ __| '_ \| |
#  \__ \ (_| (_) | |_| |_ / / (_| | (__| | | | |
#  |___/\___\___/ \__|\__/___\__,_|\___|_| |_|_|
#
#       Zac Scott (github.com/scottzach1)
#
# bspwm config file

##==========================================##
#                         *** Basic Configuration settings ***                    #
##=======================================##

sxhkd &

bspc monitor -d I II III IV V VI VII VIII

# Window Preferences
bspc config border_width          1
bspc config window_gap            12

bspc config top_padding		  0
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

# Preferences
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"

# Default Application Rules
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

bspc rule -a "File Transfer" state=floating
bspc rule -a class_name="jetbrains-idea" instancename="win0" state=floating

sh $HOME/.config/polybar/launch.sh

##==========================================##
#                              *** Autostart applications ***                      #
##=======================================##

startup() {
	# If process matches $1, execute $2
	if ! pgrep -x $1 > /dev/null
	then
		eval $2 &
	fi
}

start-pulseaudio-x11 &
startup "nm-applet"       "nm-applet"
startup "picom"           "picom -b"
startup "mullvad-vpn"     "mullvad-vpn"
startup "insync"          "insync"
startup "nextcloud"       "nextcloud"
startup "blueman-applet"  "blueman-applet"
startup "mpd-mpris"       "mpd-mpris"
startup "xautolock"       "xautolock -time 10 -corners +0-0 -locker 'betterlockscreen --lock'"
sh $HOME/unlock.sh > /dev/null &

nitrogen --restore &

# Java Application Fix
wmname LG3D &
export _JAVA_AWT_WM_NONREPARTENTING=1
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'
